

execute @s ~~~ detect ~1~1~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~1~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~1~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~1~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~1~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~1~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~1~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~1~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~1~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~1~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~1~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~1~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~1~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~1~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~1~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~1~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~1~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~1~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~1~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~1~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~1~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~1~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~1~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~1~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~1~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~1~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~1~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~1~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~1~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~1~5 water -1 tag @s add isnearwater

execute @s ~~~ detect ~1~1~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~1~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~1~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~1~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~1~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~1~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~1~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~1~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~1~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~1~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~1~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~1~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~1~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~1~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~1~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~1~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~1~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~1~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~1~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~1~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~1~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~1~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~1~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~1~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~1~-5 water -1 tag @s add isnearwater

execute @s ~~~ detect ~-1~1~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~1~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~1~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~1~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~1~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~1~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~1~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~1~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~1~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~1~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~1~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~1~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~1~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~1~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~1~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~1~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~1~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~1~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~1~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~1~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~1~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~1~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~1~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~1~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~1~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~1~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~1~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~1~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~1~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~1~5 water -1 tag @s add isnearwater

execute @s ~~~ detect ~-1~1~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~1~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~1~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~1~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~1~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~1~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~1~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~1~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~1~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~1~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~1~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~1~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~1~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~1~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~1~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~1~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~1~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~1~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~1~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~1~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~1~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~1~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~1~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~1~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~1~-5 water -1 tag @s add isnearwater


execute @s ~~~ detect ~~1~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~1~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~1~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~1~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~1~5 water -1 tag @s add isnearwater


execute @s ~~~ detect ~~1~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~1~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~1~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~1~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~1~-5 water -1 tag @s add isnearwater
