

execute @s ~~~ detect ~1~4~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~4~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~4~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~4~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~4~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~4~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~4~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~4~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~4~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~4~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~4~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~4~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~4~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~4~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~4~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~4~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~4~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~4~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~4~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~4~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~4~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~4~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~4~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~4~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~4~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~4~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~4~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~4~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~4~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~4~5 water -1 tag @s add isnearwater

execute @s ~~~ detect ~1~4~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~4~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~4~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~4~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~4~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~4~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~4~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~4~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~4~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~4~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~4~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~4~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~4~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~4~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~4~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~4~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~4~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~4~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~4~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~4~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~4~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~4~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~4~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~4~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~4~-5 water -1 tag @s add isnearwater

execute @s ~~~ detect ~-1~4~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~4~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~4~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~4~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~4~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~4~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~4~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~4~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~4~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~4~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~4~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~4~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~4~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~4~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~4~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~4~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~4~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~4~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~4~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~4~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~4~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~4~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~4~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~4~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~4~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~4~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~4~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~4~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~4~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~4~5 water -1 tag @s add isnearwater

execute @s ~~~ detect ~-1~4~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~4~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~4~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~4~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~4~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~4~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~4~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~4~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~4~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~4~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~4~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~4~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~4~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~4~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~4~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~4~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~4~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~4~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~4~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~4~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~4~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~4~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~4~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~4~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~4~-5 water -1 tag @s add isnearwater


execute @s ~~~ detect ~~4~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~4~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~4~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~4~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~4~5 water -1 tag @s add isnearwater


execute @s ~~~ detect ~~4~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~4~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~4~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~4~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~4~-5 water -1 tag @s add isnearwater
