

execute @s ~~~ detect ~1~5~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~5~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~5~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~5~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~5~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~5~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~5~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~5~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~5~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~5~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~5~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~5~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~5~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~5~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~5~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~5~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~5~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~5~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~5~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~5~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~5~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~5~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~5~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~5~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~5~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~5~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~5~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~5~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~5~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~5~5 water -1 tag @s add isnearwater

execute @s ~~~ detect ~1~5~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~5~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~5~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~5~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~5~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~5~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~5~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~5~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~5~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~5~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~5~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~5~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~5~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~5~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~5~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~5~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~5~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~5~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~5~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~5~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~5~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~5~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~5~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~5~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~5~-5 water -1 tag @s add isnearwater

execute @s ~~~ detect ~-1~5~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~5~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~5~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~5~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~5~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~5~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~5~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~5~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~5~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~5~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~5~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~5~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~5~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~5~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~5~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~5~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~5~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~5~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~5~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~5~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~5~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~5~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~5~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~5~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~5~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~5~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~5~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~5~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~5~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~5~5 water -1 tag @s add isnearwater

execute @s ~~~ detect ~-1~5~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~5~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~5~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~5~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~5~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~5~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~5~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~5~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~5~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~5~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~5~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~5~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~5~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~5~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~5~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~5~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~5~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~5~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~5~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~5~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~5~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~5~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~5~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~5~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~5~-5 water -1 tag @s add isnearwater


execute @s ~~~ detect ~~5~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~5~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~5~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~5~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~5~5 water -1 tag @s add isnearwater


execute @s ~~~ detect ~~5~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~5~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~5~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~5~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~5~-5 water -1 tag @s add isnearwater
