

execute @s ~~~ detect ~1~3~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~3~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~3~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~3~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~3~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~3~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~3~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~3~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~3~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~3~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~3~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~3~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~3~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~3~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~3~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~3~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~3~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~3~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~3~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~3~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~3~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~3~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~3~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~3~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~3~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~3~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~3~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~3~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~3~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~3~5 water -1 tag @s add isnearwater

execute @s ~~~ detect ~1~3~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~3~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~3~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~3~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~3~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~3~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~3~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~3~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~3~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~3~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~3~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~3~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~3~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~3~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~3~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~3~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~3~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~3~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~3~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~3~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~3~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~3~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~3~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~3~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~3~-5 water -1 tag @s add isnearwater

execute @s ~~~ detect ~-1~3~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~3~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~3~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~3~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~3~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~3~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~3~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~3~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~3~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~3~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~3~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~3~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~3~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~3~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~3~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~3~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~3~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~3~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~3~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~3~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~3~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~3~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~3~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~3~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~3~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~3~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~3~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~3~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~3~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~3~5 water -1 tag @s add isnearwater

execute @s ~~~ detect ~-1~3~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~3~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~3~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~3~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~3~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~3~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~3~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~3~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~3~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~3~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~3~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~3~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~3~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~3~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~3~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~3~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~3~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~3~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~3~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~3~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~3~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~3~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~3~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~3~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~3~-5 water -1 tag @s add isnearwater


execute @s ~~~ detect ~~3~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~3~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~3~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~3~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~3~5 water -1 tag @s add isnearwater


execute @s ~~~ detect ~~3~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~3~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~3~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~3~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~3~-5 water -1 tag @s add isnearwater
