

execute @s ~~~ detect ~1~~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~5 water -1 tag @s add isnearwater

execute @s ~~~ detect ~1~~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~-5 water -1 tag @s add isnearwater

execute @s ~~~ detect ~-1~~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~ water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~5 water -1 tag @s add isnearwater

execute @s ~~~ detect ~-1~~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~-5 water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~-5 water -1 tag @s add isnearwater


execute @s ~~~ detect ~~~1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~~2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~~3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~~4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~~5 water -1 tag @s add isnearwater


execute @s ~~~ detect ~~~-1 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~~-2 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~~-3 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~~-4 water -1 tag @s add isnearwater
execute @s ~~~ detect ~~~-5 water -1 tag @s add isnearwater
