

execute @s ~~~ detect ~1~-3~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-3~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-3~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-3~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-3~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-3~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-3~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-3~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-3~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-3~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-3~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-3~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-3~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-3~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-3~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-3~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-3~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-3~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-3~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-3~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-3~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-3~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-3~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-3~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-3~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-3~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-3~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-3~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-3~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-3~5 campfire -1 tag @s add isnearfire

execute @s ~~~ detect ~1~-3~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-3~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-3~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-3~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-3~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-3~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-3~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-3~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-3~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-3~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-3~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-3~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-3~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-3~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-3~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-3~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-3~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-3~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-3~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-3~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-3~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-3~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-3~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-3~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-3~-5 campfire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~-3~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-3~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-3~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-3~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-3~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-3~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-3~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-3~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-3~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-3~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-3~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-3~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-3~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-3~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-3~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-3~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-3~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-3~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-3~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-3~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-3~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-3~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-3~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-3~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-3~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-3~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-3~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-3~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-3~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-3~5 campfire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~-3~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-3~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-3~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-3~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-3~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-3~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-3~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-3~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-3~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-3~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-3~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-3~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-3~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-3~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-3~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-3~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-3~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-3~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-3~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-3~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-3~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-3~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-3~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-3~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-3~-5 campfire -1 tag @s add isnearfire


execute @s ~~~ detect ~~-3~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-3~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-3~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-3~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-3~5 campfire -1 tag @s add isnearfire


execute @s ~~~ detect ~~-3~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-3~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-3~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-3~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-3~-5 campfire -1 tag @s add isnearfire
