

execute @s ~~~ detect ~1~~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~5 campfire -1 tag @s add isnearfire

execute @s ~~~ detect ~1~~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~-5 campfire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~5 campfire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~-5 campfire -1 tag @s add isnearfire


execute @s ~~~ detect ~~~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~5 campfire -1 tag @s add isnearfire


execute @s ~~~ detect ~~~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~-5 campfire -1 tag @s add isnearfire
