

execute @s ~~~ detect ~1~-1~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~5 campfire -1 tag @s add isnearfire

execute @s ~~~ detect ~1~-1~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~-5 campfire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~-1~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~ campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~5 campfire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~-1~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~-5 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~-5 campfire -1 tag @s add isnearfire


execute @s ~~~ detect ~~-1~1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~5 campfire -1 tag @s add isnearfire


execute @s ~~~ detect ~~-1~-1 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~-2 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~-3 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~-4 campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~-5 campfire -1 tag @s add isnearfire
