kill @e[type=item,name="raw beef"]
kill @e[type=item,name="leather"]
kill @e[type=item,name="raw mutton"]
kill @e[type=item,name="white wool"]
kill @e[type=item,name="raw porkchop"]
kill @e[type=item,name="raw chicken"]
kill @e[type=item,name="feather"]
kill @e[type=item,name="poppy"]
kill @e[type=item,name="iron ingot"]
kill @e[type=item,name="blaze rod"]
kill @e[type=item,name="spider eye"]
kill @e[type=item,name="string"]
kill @e[type=item,name="bone"]
kill @e[type=item,name="arrow"]
kill @e[type=item,name="rotten flesh"]
kill @e[type=item,name="slime"]
kill @e[type=item,name="coal"]
kill @e[type=item,name="magma cream"]
kill @e[type=item,name="ender pearl"]
kill @e[type=item,name="slime"]
kill @e[type=item,name="gunpowder"]
kill @e[type=item,name="prismarine shard"]
kill @e[type=item,name="raw cod"]
kill @e[type=item,name="prismarine crystals"]