scoreboard objectives add sheepcount dummy
scoreboard objectives add sheepdespawn dummy
scoreboard objectives add blazecount dummy
scoreboard objectives add blazedespawn dummy
scoreboard objectives add chickencount dummy
scoreboard objectives add chickendespawn dummy
scoreboard objectives add cowcount dummy
scoreboard objectives add cowdespawn dummy
scoreboard objectives add irongolemcount dummy
scoreboard objectives add irongolemdespawn dummy
scoreboard objectives add endermancount dummy
scoreboard objectives add endermandespawn dummy
scoreboard objectives add pigcount dummy
scoreboard objectives add pigdespawn dummy
scoreboard objectives add skeletoncount dummy
scoreboard objectives add skeletondespawn dummy
scoreboard objectives add slimecount dummy
scoreboard objectives add slimedespawn dummy
scoreboard objectives add zombiecount dummy
scoreboard objectives add zombiedespawn dummy
scoreboard objectives add wskeletoncount dummy
scoreboard objectives add wskeletondespawn dummy
scoreboard objectives add magmacubecount dummy
scoreboard objectives add magmacubedespawn dummy
scoreboard objectives add spidercount dummy
scoreboard objectives add spiderdespawn dummy
scoreboard objectives add creepercount dummy
scoreboard objectives add creeperdespawn dummy
scoreboard objectives add guardiancount dummy
scoreboard objectives add guardiandespawn dummy

scoreboard objectives add sheep dummy
scoreboard objectives add blaze dummy
scoreboard objectives add chicken dummy
scoreboard objectives add cow dummy
scoreboard objectives add iron_golem dummy
scoreboard objectives add enderman dummy
scoreboard objectives add pig dummy
scoreboard objectives add skeleton dummy
scoreboard objectives add slime dummy
scoreboard objectives add zombie dummy
scoreboard objectives add witherskeleton dummy
scoreboard objectives add magmacube dummy
scoreboard objectives add spider dummy
scoreboard objectives add creeper dummy
scoreboard objectives add guardian dummy