

execute @s ~~~ detect ~1~~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~5 flowing_water -1 tag @s add isnearwater

execute @s ~~~ detect ~1~~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~~-5 flowing_water -1 tag @s add isnearwater

execute @s ~~~ detect ~-1~~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~5 flowing_water -1 tag @s add isnearwater

execute @s ~~~ detect ~-1~~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~~-5 flowing_water -1 tag @s add isnearwater


execute @s ~~~ detect ~~~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~~5 flowing_water -1 tag @s add isnearwater


execute @s ~~~ detect ~~~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~~-5 flowing_water -1 tag @s add isnearwater
