

execute @s ~~~ detect ~1~2~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~2~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~2~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~2~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~2~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~2~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~2~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~2~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~2~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~2~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~2~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~2~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~2~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~2~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~2~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~2~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~2~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~2~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~2~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~2~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~2~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~2~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~2~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~2~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~2~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~2~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~2~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~2~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~2~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~2~5 flowing_water -1 tag @s add isnearwater

execute @s ~~~ detect ~1~2~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~2~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~2~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~2~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~2~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~2~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~2~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~2~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~2~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~2~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~2~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~2~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~2~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~2~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~2~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~2~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~2~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~2~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~2~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~2~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~2~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~2~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~2~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~2~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~2~-5 flowing_water -1 tag @s add isnearwater

execute @s ~~~ detect ~-1~2~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~2~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~2~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~2~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~2~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~2~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~2~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~2~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~2~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~2~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~2~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~2~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~2~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~2~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~2~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~2~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~2~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~2~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~2~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~2~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~2~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~2~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~2~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~2~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~2~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~2~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~2~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~2~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~2~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~2~5 flowing_water -1 tag @s add isnearwater

execute @s ~~~ detect ~-1~2~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~2~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~2~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~2~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~2~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~2~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~2~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~2~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~2~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~2~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~2~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~2~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~2~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~2~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~2~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~2~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~2~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~2~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~2~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~2~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~2~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~2~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~2~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~2~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~2~-5 flowing_water -1 tag @s add isnearwater


execute @s ~~~ detect ~~2~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~2~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~2~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~2~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~2~5 flowing_water -1 tag @s add isnearwater


execute @s ~~~ detect ~~2~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~2~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~2~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~2~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~2~-5 flowing_water -1 tag @s add isnearwater
