

execute @s ~~~ detect ~1~-3~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~-3~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~-3~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~-3~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~-3~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~-3~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~-3~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~-3~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~-3~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~-3~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~-3~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~-3~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~-3~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~-3~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~-3~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~-3~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~-3~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~-3~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~-3~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~-3~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~-3~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~-3~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~-3~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~-3~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~-3~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~-3~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~-3~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~-3~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~-3~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~-3~5 flowing_water -1 tag @s add isnearwater

execute @s ~~~ detect ~1~-3~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~-3~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~-3~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~-3~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~-3~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~-3~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~-3~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~-3~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~-3~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~-3~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~-3~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~-3~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~-3~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~-3~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~-3~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~-3~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~-3~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~-3~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~-3~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~-3~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~1~-3~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~2~-3~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~3~-3~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~4~-3~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~5~-3~-5 flowing_water -1 tag @s add isnearwater

execute @s ~~~ detect ~-1~-3~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~-3~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~-3~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~-3~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~-3~ flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~-3~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~-3~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~-3~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~-3~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~-3~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~-3~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~-3~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~-3~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~-3~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~-3~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~-3~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~-3~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~-3~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~-3~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~-3~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~-3~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~-3~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~-3~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~-3~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~-3~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~-3~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~-3~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~-3~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~-3~5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~-3~5 flowing_water -1 tag @s add isnearwater

execute @s ~~~ detect ~-1~-3~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~-3~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~-3~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~-3~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~-3~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~-3~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~-3~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~-3~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~-3~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~-3~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~-3~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~-3~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~-3~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~-3~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~-3~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~-3~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~-3~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~-3~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~-3~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~-3~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-1~-3~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-2~-3~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-3~-3~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-4~-3~-5 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~-5~-3~-5 flowing_water -1 tag @s add isnearwater


execute @s ~~~ detect ~~-3~1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~-3~2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~-3~3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~-3~4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~-3~5 flowing_water -1 tag @s add isnearwater


execute @s ~~~ detect ~~-3~-1 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~-3~-2 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~-3~-3 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~-3~-4 flowing_water -1 tag @s add isnearwater
execute @s ~~~ detect ~~-3~-5 flowing_water -1 tag @s add isnearwater
