

execute @s ~~~ detect ~1~2~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~2~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~2~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~2~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~2~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~2~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~5 soul_campfire -1 tag @s add isnearfire

execute @s ~~~ detect ~1~2~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~2~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~2~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~2~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~2~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~-5 soul_campfire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~2~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~2~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~2~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~2~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~2~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~2~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~5 soul_campfire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~2~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~2~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~2~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~2~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~2~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~-5 soul_campfire -1 tag @s add isnearfire


execute @s ~~~ detect ~~2~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~2~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~2~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~2~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~2~5 soul_campfire -1 tag @s add isnearfire


execute @s ~~~ detect ~~2~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~2~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~2~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~2~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~2~-5 soul_campfire -1 tag @s add isnearfire
