

execute @s ~~~ detect ~1~-5~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-5~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-5~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-5~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-5~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-5~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~5 soul_campfire -1 tag @s add isnearfire

execute @s ~~~ detect ~1~-5~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-5~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-5~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-5~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-5~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~-5 soul_campfire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~-5~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-5~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-5~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-5~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-5~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-5~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~5 soul_campfire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~-5~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-5~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-5~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-5~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-5~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~-5 soul_campfire -1 tag @s add isnearfire


execute @s ~~~ detect ~~-5~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-5~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-5~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-5~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-5~5 soul_campfire -1 tag @s add isnearfire


execute @s ~~~ detect ~~-5~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-5~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-5~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-5~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-5~-5 soul_campfire -1 tag @s add isnearfire
