

execute @s ~~~ detect ~1~~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~5 soul_campfire -1 tag @s add isnearfire

execute @s ~~~ detect ~1~~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~-5 soul_campfire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~5 soul_campfire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~-5 soul_campfire -1 tag @s add isnearfire


execute @s ~~~ detect ~~~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~5 soul_campfire -1 tag @s add isnearfire


execute @s ~~~ detect ~~~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~-5 soul_campfire -1 tag @s add isnearfire
