

execute @s ~~~ detect ~1~-1~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~5 soul_campfire -1 tag @s add isnearfire

execute @s ~~~ detect ~1~-1~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~-5 soul_campfire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~-1~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~ soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~5 soul_campfire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~-1~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~-5 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~-5 soul_campfire -1 tag @s add isnearfire


execute @s ~~~ detect ~~-1~1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~5 soul_campfire -1 tag @s add isnearfire


execute @s ~~~ detect ~~-1~-1 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~-2 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~-3 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~-4 soul_campfire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~-5 soul_campfire -1 tag @s add isnearfire
