give @s wr:cracked_grimstone_tile
give @s wr:grimstone_tile
give @s wr:grimstone_copper
give @s wr:grimstone_coal
give @s wr:bone_ribs
give @s wr:corrupted_catalyst
give @s wr:trypo_vein
give @s wr:grimstone_diamond
give @s wr:rust_catalyst
give @s wr:trypo_catalyst
give @s wr:pitch_vein
give @s wr:grimstone_emerald
give @s wr:cobbled_grimstone
give @s wr:grimstone_iron
give @s wr:grow_bone
give @s wr:grimstone_lapis
give @s wr:grimstone_brick
give @s wr:cracked_grimstone_brick
give @s wr:chiseled_grimstone
give @s wr:rust
give @s wr:grimstone_gold
give @s wr:grimstone_redstone
give @s wr:rusted_vein
give @s wr:corruption2
give @s wr:fossiled_bone1
give @s wr:void_vein
give @s wr:fossile_bone2
give @s wr:corruption1
give @s wr:corrupted_sculk
give @s wr:block_of_bone
give @s wr:corrupted_vein
give @s wr:dark_void
give @s wr:corrupted_vein2
give @s wr:trypo_sensor
give @s wr:trypo_sculk
give @s wr:pitch_sculk
give @s wr:pitch_catalyst
give @s wr:trypo_shrieker
give @s wr:dark_sculk
give @s wr:bone_catalyst
give @s wr:grimstone
