give @p espadas:espada_blaze
give @p espadas:espada_nieve
give @p espadas:espada_hueso
give @p espadas:espada_oro_mejorada
give @p espadas:espada_ender_pearl
give @p espadas:espada_almas
give @p espadas:espada_wither
give @p espadas:espada_ladrillo
give @p espadas:espada_antigua
give @p espadas:espada_prismania
give @p espadas:mineral_plomo
give @p espadas:carton
give @p espadas:espada_galleta
give @p espadas:espada_papel
give @p espadas:espada_lana
give @p espadas:espada_bedrock
give @p espadas:mineral_titanio
give @p espadas:espada_netherstar
give @p espadas:lingote_estano
give @p espadas:espada_maldita
give @p espadas:rubi
give @p espadas:espada_mistica
give @p espadas:espada_inmortalidad
give @p espadas:guadana
give @p espadas:espada_cuarzo
give @p espadas:mineral_cobre
give @p espadas:espada_esmeralda
give @p espadas:espada_madera_falsa
give @p espadas:espada_slime
give @p espadas:espada_cristal
give @p espadas:cuarzo_rosa
give @p espadas:lingote_plomo
give @p espadas:botella
give @p espadas:espada_poder
give @p espadas:espada_hierro_falsa
give @p espadas:espada_nuclear
give @p espadas:espada_obsidiana
give @p espadas:espada_hielo
give @p espadas:lingote_titanio
give @p espadas:lingote_cobre
give @p espadas:espada_carbon
give @p espadas:super_espada
give @p espadas:espada_mar
give @p espadas:espada_lava
give @p espadas:espada_pedernal
give @p espadas:mineral_zafiro
give @p espadas:espada_redstone
give @p espadas:mega_sword
give @p espadas:amatista
give @p espadas:espada_hojas
give @p espadas:espada_lapislazuli
give @p espadas:espada_dano
give @p espadas:espada_tnt
give @p espadas:mineral_platino
give @p espadas:mineral_niquel
give @p espadas:espada_oro_falsa
give @p espadas:espada_infiedra
give @p espadas:espada_curativa
give @p espadas:mineral_estano
give @p espadas:espada_inframundita_falsa
give @p espadas:espada_diamante_falsa
give @p espadas:espada_carton
give @p espadas:espada_piedra_falsa
give @p espadas:mineral_rubi
give @p espadas:espada_estano
give @p espadas:espada_cobre
give @p espadas:espada_niquel
give @p espadas:espada_zafiro
give @p espadas:espada_plomo
give @p espadas:zafiro
give @p espadas:espada_platino
give @p espadas:espada_rubi
give @p espadas:mineral_cuarzo_rosa
give @p espadas:lingote_niquel
give @p espadas:diamante_blanco
give @p espadas:espada_diamante_blanco
give @p espadas:espada_amatista
give @p espadas:espada_titanio
give @p espadas:mineral_diamante_blanco
give @p espadas:espada_cuarzo_rosa
give @p espadas:lingote_platino
give @p espadas:mineral_amatista
