give @s adv:squid 64
give @s adv:catfish 64
give @s adv:pike 64
give @s adv:explosive_crucian 64
give @s adv:angelfish 64
give @s adv:jellyfish 64
give @s adv:sponge_eater 64
give @s adv:sandy_bass 64
give @s adv:golden_koi 64
give @s adv:sunfish 64
give @s adv:snowy_walleye 64
give @s adv:frost_minnow 64
give @s adv:glacier_anchovy 64
give @s adv:abyssal_lurker 64
give @s adv:angler_fish 64
give @s adv:specular_snapper 64
give @s adv:cave_trout 64
give @s adv:crystal_mullet 64
give @s adv:charged_bullhead 64
give @s adv:piranha 64
give @s adv:sparkling_eel 64
give @s adv:mandarinfish 64
give @s adv:ruffe 64
give @s adv:mud_tuna 64
give @s adv:swamp_plaice 64
give @s adv:brown_shroomfin 64
give @s adv:red_shroomfin 64
give @s adv:ender_shad 64
give @s adv:pearl_sardine 64
give @s adv:chorus_koi 64