

execute @s ~~~ detect ~1~-1~ flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-1~ flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-1~ flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-1~ flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-1~ flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~-1~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-1~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-1~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-1~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-1~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~-1~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-1~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-1~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-1~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-1~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~-1~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-1~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-1~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-1~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-1~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~-1~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-1~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-1~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-1~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-1~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~-1~5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-1~5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-1~5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-1~5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-1~5 flowing_lava -1 tag @s add isnearlava

execute @s ~~~ detect ~1~-1~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-1~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-1~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-1~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-1~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~-1~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-1~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-1~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-1~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-1~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~-1~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-1~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-1~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-1~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-1~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~-1~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-1~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-1~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-1~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-1~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~-1~-5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-1~-5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-1~-5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-1~-5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-1~-5 flowing_lava -1 tag @s add isnearlava

execute @s ~~~ detect ~-1~-1~ flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-1~ flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-1~ flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-1~ flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-1~ flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~-1~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-1~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-1~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-1~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-1~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~-1~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-1~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-1~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-1~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-1~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~-1~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-1~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-1~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-1~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-1~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~-1~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-1~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-1~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-1~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-1~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~-1~5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-1~5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-1~5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-1~5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-1~5 flowing_lava -1 tag @s add isnearlava

execute @s ~~~ detect ~-1~-1~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-1~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-1~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-1~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-1~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~-1~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-1~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-1~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-1~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-1~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~-1~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-1~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-1~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-1~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-1~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~-1~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-1~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-1~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-1~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-1~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~-1~-5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-1~-5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-1~-5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-1~-5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-1~-5 flowing_lava -1 tag @s add isnearlava


execute @s ~~~ detect ~~-1~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~-1~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~-1~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~-1~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~-1~5 flowing_lava -1 tag @s add isnearlava


execute @s ~~~ detect ~~-1~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~-1~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~-1~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~-1~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~-1~-5 flowing_lava -1 tag @s add isnearlava
