

execute @s ~~~ detect ~1~-5~ flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-5~ flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-5~ flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-5~ flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-5~ flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~-5~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-5~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-5~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-5~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-5~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~-5~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-5~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-5~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-5~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-5~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~-5~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-5~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-5~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-5~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-5~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~-5~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-5~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-5~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-5~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-5~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~-5~5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-5~5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-5~5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-5~5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-5~5 flowing_lava -1 tag @s add isnearlava

execute @s ~~~ detect ~1~-5~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-5~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-5~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-5~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-5~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~-5~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-5~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-5~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-5~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-5~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~-5~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-5~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-5~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-5~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-5~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~-5~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-5~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-5~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-5~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-5~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~-5~-5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~-5~-5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~-5~-5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~-5~-5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~-5~-5 flowing_lava -1 tag @s add isnearlava

execute @s ~~~ detect ~-1~-5~ flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-5~ flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-5~ flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-5~ flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-5~ flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~-5~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-5~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-5~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-5~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-5~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~-5~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-5~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-5~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-5~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-5~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~-5~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-5~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-5~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-5~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-5~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~-5~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-5~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-5~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-5~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-5~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~-5~5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-5~5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-5~5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-5~5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-5~5 flowing_lava -1 tag @s add isnearlava

execute @s ~~~ detect ~-1~-5~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-5~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-5~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-5~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-5~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~-5~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-5~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-5~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-5~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-5~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~-5~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-5~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-5~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-5~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-5~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~-5~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-5~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-5~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-5~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-5~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~-5~-5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~-5~-5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~-5~-5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~-5~-5 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~-5~-5 flowing_lava -1 tag @s add isnearlava


execute @s ~~~ detect ~~-5~1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~-5~2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~-5~3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~-5~4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~-5~5 flowing_lava -1 tag @s add isnearlava


execute @s ~~~ detect ~~-5~-1 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~-5~-2 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~-5~-3 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~-5~-4 flowing_lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~-5~-5 flowing_lava -1 tag @s add isnearlava
