

execute @s ~~~ detect ~1~2~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~2~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~2~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~2~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~2~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~2~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~5 fire -1 tag @s add isnearfire

execute @s ~~~ detect ~1~2~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~2~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~2~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~2~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~2~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~2~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~2~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~2~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~2~-5 fire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~2~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~2~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~2~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~2~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~2~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~2~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~5 fire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~2~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~2~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~2~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~2~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~2~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~2~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~2~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~2~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~2~-5 fire -1 tag @s add isnearfire


execute @s ~~~ detect ~~2~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~2~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~2~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~2~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~2~5 fire -1 tag @s add isnearfire


execute @s ~~~ detect ~~2~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~2~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~2~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~2~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~2~-5 fire -1 tag @s add isnearfire
