

execute @s ~~~ detect ~1~-1~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~5 fire -1 tag @s add isnearfire

execute @s ~~~ detect ~1~-1~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-1~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-1~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-1~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-1~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-1~-5 fire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~-1~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~5 fire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~-1~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-1~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-1~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-1~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-1~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-1~-5 fire -1 tag @s add isnearfire


execute @s ~~~ detect ~~-1~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~5 fire -1 tag @s add isnearfire


execute @s ~~~ detect ~~-1~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-1~-5 fire -1 tag @s add isnearfire
