

execute @s ~~~ detect ~1~-5~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-5~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-5~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-5~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-5~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-5~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~5 fire -1 tag @s add isnearfire

execute @s ~~~ detect ~1~-5~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-5~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-5~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-5~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~-5~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~-5~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~-5~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~-5~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~-5~-5 fire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~-5~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-5~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-5~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-5~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-5~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-5~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~5 fire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~-5~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-5~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-5~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-5~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~-5~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~-5~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~-5~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~-5~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~-5~-5 fire -1 tag @s add isnearfire


execute @s ~~~ detect ~~-5~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-5~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-5~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-5~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-5~5 fire -1 tag @s add isnearfire


execute @s ~~~ detect ~~-5~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-5~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-5~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-5~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~-5~-5 fire -1 tag @s add isnearfire
