

execute @s ~~~ detect ~1~~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~5 fire -1 tag @s add isnearfire

execute @s ~~~ detect ~1~~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~1~~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~2~~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~3~~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~4~~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~5~~-5 fire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~ fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~5 fire -1 tag @s add isnearfire

execute @s ~~~ detect ~-1~~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-1~~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-2~~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-3~~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-4~~-5 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~-5~~-5 fire -1 tag @s add isnearfire


execute @s ~~~ detect ~~~1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~5 fire -1 tag @s add isnearfire


execute @s ~~~ detect ~~~-1 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~-2 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~-3 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~-4 fire -1 tag @s add isnearfire
execute @s ~~~ detect ~~~-5 fire -1 tag @s add isnearfire
