

execute @s ~~~ detect ~1~~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~~5 lava -1 tag @s add isnearlava

execute @s ~~~ detect ~1~~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~~-5 lava -1 tag @s add isnearlava

execute @s ~~~ detect ~-1~~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~~5 lava -1 tag @s add isnearlava

execute @s ~~~ detect ~-1~~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~~-5 lava -1 tag @s add isnearlava


execute @s ~~~ detect ~~~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~~5 lava -1 tag @s add isnearlava


execute @s ~~~ detect ~~~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~~-5 lava -1 tag @s add isnearlava
