

execute @s ~~~ detect ~1~3~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~3~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~3~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~3~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~3~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~3~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~3~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~3~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~3~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~3~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~3~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~3~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~3~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~3~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~3~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~3~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~3~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~3~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~3~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~3~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~3~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~3~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~3~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~3~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~3~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~3~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~3~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~3~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~3~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~3~5 lava -1 tag @s add isnearlava

execute @s ~~~ detect ~1~3~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~3~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~3~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~3~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~3~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~3~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~3~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~3~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~3~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~3~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~3~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~3~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~3~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~3~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~3~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~3~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~3~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~3~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~3~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~3~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~3~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~3~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~3~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~3~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~3~-5 lava -1 tag @s add isnearlava

execute @s ~~~ detect ~-1~3~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~3~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~3~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~3~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~3~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~3~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~3~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~3~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~3~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~3~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~3~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~3~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~3~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~3~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~3~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~3~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~3~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~3~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~3~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~3~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~3~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~3~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~3~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~3~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~3~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~3~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~3~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~3~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~3~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~3~5 lava -1 tag @s add isnearlava

execute @s ~~~ detect ~-1~3~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~3~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~3~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~3~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~3~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~3~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~3~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~3~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~3~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~3~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~3~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~3~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~3~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~3~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~3~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~3~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~3~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~3~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~3~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~3~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~3~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~3~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~3~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~3~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~3~-5 lava -1 tag @s add isnearlava


execute @s ~~~ detect ~~3~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~3~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~3~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~3~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~3~5 lava -1 tag @s add isnearlava


execute @s ~~~ detect ~~3~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~3~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~3~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~3~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~3~-5 lava -1 tag @s add isnearlava
