

execute @s ~~~ detect ~1~2~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~2~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~2~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~2~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~2~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~2~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~2~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~2~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~2~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~2~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~2~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~2~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~2~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~2~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~2~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~2~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~2~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~2~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~2~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~2~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~2~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~2~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~2~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~2~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~2~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~2~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~2~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~2~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~2~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~2~5 lava -1 tag @s add isnearlava

execute @s ~~~ detect ~1~2~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~2~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~2~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~2~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~2~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~2~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~2~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~2~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~2~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~2~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~2~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~2~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~2~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~2~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~2~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~2~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~2~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~2~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~2~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~2~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~1~2~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~2~2~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~3~2~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~4~2~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~5~2~-5 lava -1 tag @s add isnearlava

execute @s ~~~ detect ~-1~2~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~2~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~2~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~2~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~2~ lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~2~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~2~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~2~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~2~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~2~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~2~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~2~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~2~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~2~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~2~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~2~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~2~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~2~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~2~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~2~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~2~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~2~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~2~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~2~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~2~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~2~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~2~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~2~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~2~5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~2~5 lava -1 tag @s add isnearlava

execute @s ~~~ detect ~-1~2~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~2~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~2~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~2~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~2~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~2~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~2~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~2~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~2~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~2~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~2~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~2~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~2~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~2~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~2~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~2~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~2~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~2~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~2~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~2~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-1~2~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-2~2~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-3~2~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-4~2~-5 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~-5~2~-5 lava -1 tag @s add isnearlava


execute @s ~~~ detect ~~2~1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~2~2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~2~3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~2~4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~2~5 lava -1 tag @s add isnearlava


execute @s ~~~ detect ~~2~-1 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~2~-2 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~2~-3 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~2~-4 lava -1 tag @s add isnearlava
execute @s ~~~ detect ~~2~-5 lava -1 tag @s add isnearlava
